const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,key='abyss-hx07';
const state={found:new Set(),visited:new Set(),decoded:false,sonar:false,max:0};var ambientFilter;
try{const s=JSON.parse(localStorage.getItem(key));if(s){state.found=new Set(s.found||[]);state.visited=new Set(s.visited||[]);state.decoded=!!s.decoded;state.sonar=!!s.sonar;state.max=+s.max||0}}catch(_){}
const save=()=>localStorage.setItem(key,JSON.stringify({found:[...state.found],visited:[...state.visited],decoded:state.decoded,sonar:state.sonar,max:state.max}));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function render(){const discoveries=state.found.size+Number(state.decoded),total=discoveries+state.visited.size;$('#logCount').textContent=discoveries;$('#found').textContent=`${state.found.size} / 3`;$('#maxDepth').textContent=`${String(state.max).padStart(4,'0')} M`;$('#progressText').textContent=`任务进度 ${Math.round(total/8*100)}%`;$('#progressBar').style.width=`${total/8*100}%`;$$('[data-visited]').forEach(el=>el.classList.toggle('found',state.visited.has(el.dataset.visited)));
  $$('[data-log]').forEach(el=>{const name=el.dataset.log,ok=state.found.has(name)||(name==='未知信号'&&state.decoded);el.classList.toggle('found',ok);if(ok){el.querySelector('b').textContent=name;el.querySelector('small').textContent=name==='未知信号'?'深渊区 · 档案已解密':'物种档案 · 已完成记录'}});
  $$('.specimen').forEach(el=>{const b=el.querySelector('.discover');if(state.found.has(el.dataset.name)){b.textContent='已收录 ✓';b.disabled=true}});if(state.decoded)$('#decoded').classList.add('show');if(state.sonar){$('#sonar').classList.add('done');$('#sonarTitle').textContent='检测到两个移动目标';$('#sonarResult').textContent='距离 182 m / 方向 047° / 正缓慢远离';$('#sonarButton').textContent='重新扫描'}}
render();
let diveProgress=0,lastMilestone=0;const milestones=[{d:200,t:'阳光边界已通过'},{d:1000,t:'自然光线已完全消失'},{d:4000,t:'进入深渊带'},{d:6000,t:'进入超深渊带'}];
// Anchor depth to dive chapters so new reading sections do not stretch the descent.
const depthStops=[['surface',0],['sunlight',0],['twilight',200],['midnight',1000],['hadal',4000],['scaleChapter',6200]];
function currentDepth(){let previous={top:0,depth:0};for(const [id,depth] of depthStops){const top=document.getElementById(id).getBoundingClientRect().top+scrollY;if(scrollY<top)return Math.round(previous.depth+(depth-previous.depth)*Math.max(0,scrollY-previous.top)/Math.max(1,top-previous.top));previous={top,depth}}return 6200}
function showMilestone(item){if(reduced)return;$('#milestoneDepth').textContent=`${item.d.toLocaleString()} M`;$('#milestoneText').textContent=item.t;$('#milestone').classList.add('show');clearTimeout(showMilestone.timer);showMilestone.timer=setTimeout(()=>$('#milestone').classList.remove('show'),1900)}
let ticking=false;function telemetry(){const d=currentDepth(),p=d/6200;diveProgress=p;document.documentElement.style.setProperty('--descent',p.toFixed(3));$('#descentProgress').style.height=`${p*100}%`;if(ambientFilter&&audioContext)ambientFilter.frequency.setTargetAtTime(210-p*135,audioContext.currentTime,.2);let z='海平面';if(d>=6000)z='超深渊带';else if(d>=4000)z='深渊区';else if(d>=1000)z='午夜区';else if(d>=200)z='暮光区';else if(d>5)z='阳光区';$('#depth').textContent=String(d).padStart(4,'0');$('#zone').textContent=z;$('#pressure').textContent=`${(1+d/10).toFixed(1)} atm`;$('#temp').textContent=`${Math.max(1.7,24-d*.0052).toFixed(1)} °C`;$('#visibility').textContent=`${Math.max(1,Math.round(100*Math.exp(-d/740)))}%`;$('#marker').style.top=`${p*100}%`;$('#telemetry').classList.toggle('show',scrollY>innerHeight*.55&&scrollY<$('#knowledge').offsetTop-innerHeight*.25);const crossed=[...milestones].reverse().find(m=>d>=m.d&&lastMilestone<m.d);if(crossed){lastMilestone=crossed.d;showMilestone(crossed)}if(d>state.max){state.max=d;$('#maxDepth').textContent=`${String(d).padStart(4,'0')} M`;if(d%25===0)save()}ticking=false}
addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(telemetry);ticking=true}},{passive:true});telemetry();
const zoneNames={sunlight:'阳光区',twilight:'暮光区',midnight:'午夜区',hadal:'深渊区'};const zoneObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const name=zoneNames[entry.target.id];if(name&&!state.visited.has(name)){state.visited.add(name);save();render();toast(`已进入${name}`)}}}),{threshold:.18});$$('.zone').forEach(zone=>zoneObserver.observe(zone));
const chapterObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;$$('.chapter-nav a').forEach(link=>link.setAttribute('aria-current',String(link.dataset.chapter===entry.target.id)))}),{rootMargin:'-42% 0px -48% 0px'});['surface','sunlight','twilight','midnight','hadal','scaleChapter','knowledge','cinema'].forEach(id=>chapterObserver.observe(document.getElementById(id)));
$('#dive').onclick=()=>{if(reduced){$('#sunlight').scrollIntoView();return}document.body.classList.add('dive-init');setTimeout(()=>$('#sunlight').scrollIntoView({behavior:'smooth'}),650);setTimeout(()=>document.body.classList.remove('dive-init'),2200)};$('#return').onclick=()=>$('#surface').scrollIntoView({behavior:reduced?'auto':'smooth'});
$$('.discover').forEach(b=>b.onclick=()=>{const card=b.closest('.specimen'),name=card.dataset.name;card.classList.add('scanned');setTimeout(()=>card.classList.remove('scanned'),950);ping(320,.6);state.found.add(name);save();render();toast(`${name} 已写入探索日志`)});
let busy=false;$('#sonarButton').onclick=()=>{if(busy)return;busy=true;ping(210,1.6);const s=$('#sonar'),blast=document.createElement('i');blast.className='sonar-blast';document.body.append(blast);setTimeout(()=>blast.remove(),1300);s.classList.remove('done','scan');void s.offsetWidth;s.classList.add('scan');$('#sonarTitle').textContent='正在扫描水体…';$('#sonarResult').textContent='发射脉冲 · 等待回波';setTimeout(()=>{s.classList.remove('scan');s.classList.add('done');state.sonar=true;busy=false;save();render();toast('声呐回波已完成分析')},reduced?100:4200)};
$('#decode').onclick=()=>{state.decoded=true;save();render();ping(70,2.4);createSignalFragments();document.body.classList.add('signal-event');setTimeout(()=>document.body.classList.remove('signal-event'),900);$('#decoded').scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'});toast('未知信号档案已解密')};
const log=$('#log'),scrim=$('#scrim');log.setAttribute('inert','');let lastFocus;function toggleLog(open){if(open)lastFocus=document.activeElement;log.classList.toggle('open',open);scrim.classList.toggle('show',open);log.setAttribute('aria-hidden',String(!open));log.toggleAttribute('inert',!open);$('#logOpen').setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';if(open)$('#logClose').focus();else lastFocus?.focus()}
$('#logOpen').onclick=()=>toggleLog(true);$('#logClose').onclick=()=>toggleLog(false);scrim.onclick=()=>toggleLog(false);addEventListener('keydown',e=>{if(e.key==='Escape'&&log.classList.contains('open'))toggleLog(false)});$('#clear').onclick=()=>{localStorage.removeItem(key);location.reload()};
log.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const focusable=$$('button:not(:disabled),a[href]').filter(el=>log.contains(el)),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});addEventListener('pagehide',save);
let audioContext,masterGain,soundOn=false;function initAudio(){audioContext=new(window.AudioContext||window.webkitAudioContext)();masterGain=audioContext.createGain();masterGain.gain.value=.0001;masterGain.connect(audioContext.destination);const droneGain=audioContext.createGain();droneGain.gain.value=.16;droneGain.connect(masterGain);[38,57].forEach((frequency,i)=>{const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();oscillator.type=i?'sine':'triangle';oscillator.frequency.value=frequency;gain.gain.value=i?.08:.12;oscillator.connect(gain).connect(droneGain);oscillator.start()});const buffer=audioContext.createBuffer(1,audioContext.sampleRate*2,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*.24;const noise=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter(),noiseGain=audioContext.createGain();ambientFilter=filter;noise.buffer=buffer;noise.loop=true;filter.type='lowpass';filter.frequency.value=180;noiseGain.gain.value=.1;noise.connect(filter).connect(noiseGain).connect(masterGain);noise.start()}
function ping(frequency=160,duration=1.2){if(!soundOn||!audioContext)return;const oscillator=audioContext.createOscillator(),gain=audioContext.createGain(),now=audioContext.currentTime;oscillator.type='sine';oscillator.frequency.setValueAtTime(frequency,now);oscillator.frequency.exponentialRampToValueAtTime(frequency*.55,now+duration);gain.gain.setValueAtTime(.18,now);gain.gain.exponentialRampToValueAtTime(.0001,now+duration);oscillator.connect(gain).connect(masterGain);oscillator.start(now);oscillator.stop(now+duration)}
$('#soundToggle').onclick=async()=>{if(!audioContext)initAudio();await audioContext.resume();soundOn=!soundOn;masterGain.gain.cancelScheduledValues(audioContext.currentTime);masterGain.gain.linearRampToValueAtTime(soundOn?.22:.0001,audioContext.currentTime+.35);$('#soundToggle').setAttribute('aria-pressed',String(soundOn));$('#soundToggle').querySelector('b').textContent=soundOn?'ON':'OFF';document.body.classList.toggle('audio-on',soundOn);if(soundOn)ping(120,.8)};
$('#screenToggle').onclick=async()=>{try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen()}catch(_){toast('当前浏览器不支持全屏模式')}};addEventListener('fullscreenchange',()=>{$('#screenToggle').textContent=document.fullscreenElement?'退出全屏':'全屏'});
const field=$('#biolume');for(let i=0;i<26;i++){const d=document.createElement('i');d.className='bio';d.style.left=`${6+Math.random()*88}%`;d.style.top=`${7+Math.random()*86}%`;d.style.opacity=.25+Math.random()*.7;d.style.scale=.6+Math.random()*1.4;field.append(d)}if(!reduced)field.onpointermove=e=>{const r=field.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$$('.bio').forEach((d,i)=>d.style.translate=`${x*(i%5+5)}px ${y*(i%4+5)}px`)};
for(let i=0;i<8;i++){const jelly=document.createElement('span');jelly.className='jelly';jelly.style.left=`${5+Math.random()*88}%`;jelly.style.top=`${30+Math.random()*58}%`;jelly.style.setProperty('--size',`${26+Math.random()*48}px`);jelly.style.setProperty('--alpha',.18+Math.random()*.42);jelly.style.setProperty('--duration',`${7+Math.random()*7}s`);jelly.style.setProperty('--delay',`${-Math.random()*9}s`);jelly.innerHTML='<i></i><b></b><em></em>';field.append(jelly)}
for(let i=0;i<18;i++){const fish=document.createElement('i');fish.className='school-fish';fish.style.left=`${-20+Math.random()*90}%`;fish.style.top=`${35+Math.random()*48}%`;fish.style.setProperty('--size',`${7+Math.random()*16}px`);fish.style.setProperty('--speed',`${12+Math.random()*15}s`);fish.style.setProperty('--delay',`${-Math.random()*22}s`);fish.style.opacity=.18+Math.random()*.48;$('#sunlight').append(fish)}
for(let i=0;i<15;i++){const bubble=document.createElement('i');bubble.className='bubble';bubble.style.setProperty('--left',`${3+Math.random()*94}%`);bubble.style.setProperty('--size',`${3+Math.random()*13}px`);bubble.style.setProperty('--speed',`${6+Math.random()*9}s`);bubble.style.setProperty('--delay',`${-Math.random()*12}s`);$('#surface').append(bubble)}
function createSignalFragments(){if(reduced)return;const glyphs='0101⌁∆Ω深海未知';for(let i=0;i<28;i++){const fragment=document.createElement('i');fragment.className='signal-fragment';fragment.textContent=glyphs[Math.floor(Math.random()*glyphs.length)];fragment.style.setProperty('--x',`${35+Math.random()*55}%`);fragment.style.setProperty('--y',`${45+Math.random()*40}%`);fragment.style.setProperty('--dx',`${(Math.random()-.5)*320}px`);fragment.style.setProperty('--dy',`${-80-Math.random()*260}px`);fragment.style.setProperty('--size',`${7+Math.random()*13}px`);$('#hadal').append(fragment);setTimeout(()=>fragment.remove(),2500)}}
const scaleObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.2});scaleObserver.observe($('#scaleChapter'));
const pressureLine=document.createElement('div');pressureLine.className='pressure-line';document.body.append(pressureLine);const revealObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('in-view',e.isIntersecting)),{threshold:.12});$$('.zone .heading,.specimen,.zone-data,.observation,.sonar-wrap,.signal-console').forEach(el=>{el.classList.add('js-reveal');revealObserver.observe(el)});
for(let i=0;i<9;i++){const vent=document.createElement('i');vent.className='vent';vent.style.left=`${3+i*12+Math.random()*5}%`;vent.style.setProperty('--w',`${18+Math.random()*38}px`);vent.style.setProperty('--h',`${70+Math.random()*170}px`);vent.style.opacity=.45+Math.random()*.45;$('#ventField').append(vent)}
if(!reduced)addEventListener('pointermove',e=>{$('#cursorLight').style.left=`${e.clientX}px`;$('#cursorLight').style.top=`${e.clientY}px`},{passive:true});
if(!reduced)addEventListener('pointerdown',e=>{if(e.button!==0)return;const ripple=document.createElement('i');ripple.className='touch-ripple';ripple.style.setProperty('--x',`${e.clientX}px`);ripple.style.setProperty('--y',`${e.clientY}px`);document.body.append(ripple);setTimeout(()=>ripple.remove(),800)},{passive:true});
const canvas=$('#particles'),ctx=canvas.getContext('2d');let ps=[];function resize(){const r=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*r;canvas.height=innerHeight*r;ctx.setTransform(r,0,0,r,0,0);ps=Array.from({length:innerWidth<700?32:68},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.8+.3,s:Math.random()*.32+.06,d:Math.random()*.35-.175,a:Math.random()*.45+.15,ring:Math.random()>.84}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of ps){ctx.beginPath();ctx.globalAlpha=p.a*(.8+diveProgress*.45);ctx.strokeStyle='#8cfff1';ctx.fillStyle='#adf6f5';ctx.arc(p.x,p.y,p.r*(1+diveProgress*.8),0,Math.PI*2);p.ring?ctx.stroke():ctx.fill();p.y-=p.s*(1+diveProgress*2.2);p.x+=p.d+Math.sin(p.y*.012)*.08;if(p.y<-5){p.y=innerHeight+5;p.x=Math.random()*innerWidth}}ctx.globalAlpha=1;if(!reduced&&!document.hidden)requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize,{passive:true});
