const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,key='abyss-hx07';
const state={found:new Set(),visited:new Set(),decoded:false,sonar:false,max:0};
try{const s=JSON.parse(localStorage.getItem(key));if(s){state.found=new Set(s.found||[]);state.visited=new Set(s.visited||[]);state.decoded=!!s.decoded;state.sonar=!!s.sonar;state.max=+s.max||0}}catch(_){}
const save=()=>localStorage.setItem(key,JSON.stringify({found:[...state.found],visited:[...state.visited],decoded:state.decoded,sonar:state.sonar,max:state.max}));
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2100)}
function render(){const discoveries=state.found.size+Number(state.decoded),total=discoveries+state.visited.size;$('#logCount').textContent=discoveries;$('#found').textContent=`${state.found.size} / 3`;$('#maxDepth').textContent=`${String(state.max).padStart(4,'0')} M`;$('#progressText').textContent=`任务进度 ${Math.round(total/8*100)}%`;$('#progressBar').style.width=`${total/8*100}%`;$$('[data-visited]').forEach(el=>el.classList.toggle('found',state.visited.has(el.dataset.visited)));
  $$('[data-log]').forEach(el=>{const name=el.dataset.log,ok=state.found.has(name)||(name==='未知信号'&&state.decoded);el.classList.toggle('found',ok);if(ok){el.querySelector('b').textContent=name;el.querySelector('small').textContent=name==='未知信号'?'深渊区 · 档案已解密':'物种档案 · 已完成记录'}});
  $$('.specimen').forEach(el=>{const b=el.querySelector('.discover');if(state.found.has(el.dataset.name)){b.textContent='已收录 ✓';b.disabled=true}});if(state.decoded)$('#decoded').classList.add('show');if(state.sonar){$('#sonar').classList.add('done');$('#sonarTitle').textContent='检测到两个移动目标';$('#sonarResult').textContent='距离 182 m / 方向 047° / 正缓慢远离';$('#sonarButton').textContent='重新扫描'}}
render();
let ticking=false;function telemetry(){const max=document.documentElement.scrollHeight-innerHeight,p=Math.min(1,Math.max(0,scrollY/Math.max(1,max*.86))),d=Math.round(6200*Math.pow(p,.82));let z='海平面';if(d>4000)z='深渊区';else if(d>1000)z='午夜区';else if(d>200)z='暮光区';else if(d>5)z='阳光区';$('#depth').textContent=String(d).padStart(4,'0');$('#zone').textContent=z;$('#pressure').textContent=`${(1+d/10).toFixed(1)} atm`;$('#temp').textContent=`${Math.max(1.7,24-d*.0052).toFixed(1)} °C`;$('#visibility').textContent=`${Math.max(1,Math.round(100*Math.exp(-d/740)))}%`;$('#marker').style.top=`${p*100}%`;$('#telemetry').classList.toggle('show',scrollY>innerHeight*.55&&scrollY<max-innerHeight*.3);if(d>state.max){state.max=d;$('#maxDepth').textContent=`${String(d).padStart(4,'0')} M`;if(d%25===0)save()}ticking=false}
addEventListener('scroll',()=>{if(!ticking){requestAnimationFrame(telemetry);ticking=true}},{passive:true});telemetry();
const zoneNames={sunlight:'阳光区',twilight:'暮光区',midnight:'午夜区',hadal:'深渊区'};const zoneObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){const name=zoneNames[entry.target.id];if(name&&!state.visited.has(name)){state.visited.add(name);save();render();toast(`已进入${name}`)}}}),{threshold:.18});$$('.zone').forEach(zone=>zoneObserver.observe(zone));
$('#dive').onclick=()=>$('#sunlight').scrollIntoView({behavior:reduced?'auto':'smooth'});$('#return').onclick=()=>$('#surface').scrollIntoView({behavior:reduced?'auto':'smooth'});
$$('.discover').forEach(b=>b.onclick=()=>{const name=b.closest('.specimen').dataset.name;state.found.add(name);save();render();toast(`${name} 已写入探索日志`)});
let busy=false;$('#sonarButton').onclick=()=>{if(busy)return;busy=true;const s=$('#sonar');s.classList.remove('done','scan');void s.offsetWidth;s.classList.add('scan');$('#sonarTitle').textContent='正在扫描水体…';$('#sonarResult').textContent='发射脉冲 · 等待回波';setTimeout(()=>{s.classList.remove('scan');s.classList.add('done');state.sonar=true;busy=false;save();render();toast('声呐回波已完成分析')},reduced?100:4200)};
$('#decode').onclick=()=>{state.decoded=true;save();render();$('#decoded').scrollIntoView({behavior:reduced?'auto':'smooth',block:'nearest'});toast('未知信号档案已解密')};
const log=$('#log'),scrim=$('#scrim');log.setAttribute('inert','');let lastFocus;function toggleLog(open){if(open)lastFocus=document.activeElement;log.classList.toggle('open',open);scrim.classList.toggle('show',open);log.setAttribute('aria-hidden',String(!open));log.toggleAttribute('inert',!open);$('#logOpen').setAttribute('aria-expanded',String(open));document.body.style.overflow=open?'hidden':'';if(open)$('#logClose').focus();else lastFocus?.focus()}
$('#logOpen').onclick=()=>toggleLog(true);$('#logClose').onclick=()=>toggleLog(false);scrim.onclick=()=>toggleLog(false);addEventListener('keydown',e=>{if(e.key==='Escape'&&log.classList.contains('open'))toggleLog(false)});$('#clear').onclick=()=>{localStorage.removeItem(key);location.reload()};
log.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const focusable=$$('button:not(:disabled),a[href]').filter(el=>log.contains(el)),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}});addEventListener('pagehide',save);
const field=$('#biolume');for(let i=0;i<26;i++){const d=document.createElement('i');d.className='bio';d.style.left=`${6+Math.random()*88}%`;d.style.top=`${7+Math.random()*86}%`;d.style.opacity=.25+Math.random()*.7;d.style.scale=.6+Math.random()*1.4;field.append(d)}if(!reduced)field.onpointermove=e=>{const r=field.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;$$('.bio').forEach((d,i)=>d.style.translate=`${x*(i%5+5)}px ${y*(i%4+5)}px`)};
const canvas=$('#particles'),ctx=canvas.getContext('2d');let ps=[];function resize(){const r=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*r;canvas.height=innerHeight*r;ctx.setTransform(r,0,0,r,0,0);ps=Array.from({length:innerWidth<700?26:52},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:Math.random()*1.5+.3,s:Math.random()*.27+.07,d:Math.random()*.3-.15}))}function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);ctx.fillStyle='#adf6f560';for(const p of ps){ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();p.y-=p.s;p.x+=p.d;if(p.y<-3){p.y=innerHeight+3;p.x=Math.random()*innerWidth}}if(!reduced&&!document.hidden)requestAnimationFrame(draw)}resize();draw();addEventListener('resize',resize,{passive:true});
